concurrent.CompletableFuture.completeExceptionally(ThrowableÂ ex)\n and related methods to throw the given exception.\n