concurrent.ForkJoinTask.getException()\nReturns the exception thrown by the base computation, or a\n CancellationException if cancelled, or null if\n none or if the method has not yet completed.\n